// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbmB-LOO1vZoJtfTERaviH9Vs4DANT4r0',
    appId: '1:799064857602:web:c9fafe402de69a22819b1b',
    messagingSenderId: '799064857602',
    projectId: 'videoshare-53458',
    authDomain: 'videoshare-53458.firebaseapp.com',
    storageBucket: 'videoshare-53458.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDheXFNOMVMdH0hjU3pK1z8Ly1cDuireHQ',
    appId: '1:799064857602:android:902f486f2f989182819b1b',
    messagingSenderId: '799064857602',
    projectId: 'videoshare-53458',
    storageBucket: 'videoshare-53458.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmFpmLI-29BGoJQjDWaHZKnmqIHPqUtKU',
    appId: '1:799064857602:ios:a0f15764148d226a819b1b',
    messagingSenderId: '799064857602',
    projectId: 'videoshare-53458',
    storageBucket: 'videoshare-53458.appspot.com',
    iosClientId: '799064857602-b3rvjq77kh5foenvb8u2lrg23nrg2kc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmFpmLI-29BGoJQjDWaHZKnmqIHPqUtKU',
    appId: '1:799064857602:ios:47bd4cb95a7f9d85819b1b',
    messagingSenderId: '799064857602',
    projectId: 'videoshare-53458',
    storageBucket: 'videoshare-53458.appspot.com',
    iosClientId: '799064857602-gksuj8gkq9dudpmtpsp2rduk7hg848a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoplayer.RunnerTests',
  );
}
